server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/ricardogtv/ms-tutorial01.git
          search-paths: config-data

  application:
    name: config-service
